DEFAULT_USER_LIST       = [
    # 32char (128bit) hex-string representation of the UUID: double sha256 of the first email-address-string
    {"username": "sziller",
     "psswd_hsh": "$2b$12$0uSgOLr3QOYVyDr8cZoOLe/sGKJPCyGwdgSrujADtD2ipS15XgJ5W",
     "email": "szillerke@gmail.com",
     "usr_fn": "Szilard",
     "usr_ln": "Ladanyi",
     "auth_code": 63,
     "pubkey": "",
     "email_arch": [],
     "uuid": "01",
     "timestamp": 0.0,
     "disabled": False},
    {"username": "mok",
     "psswd_hsh": "$2b$12$LDvH8I4wsTqAAvccpkKtzeeIGzIp/LQQ3RodBJw3kyf4UfRX3ta8C",
     "email": "mterez@gmail.com",
     "usr_fn": "Terez",
     "usr_ln": "Molnar",
     "auth_code": 15,
     "pubkey": "",
     "email_arch": [],
     "uuid": "02",
     "timestamp": 0.0,
     "disabled": False},
    {"username": "guest",
     "psswd_hsh": "$2b$12$D9CqfJm.z6h8EXI9uMrcneMidCQBTVNm5gArh5i2r450rpz7UtC9y",
     "email": "noreply@xxx.com",
     "usr_fn": "---",
     "usr_ln": "---",
     "auth_code": 0,
     "pubkey": "",
     "email_arch": [],
     "uuid": "100",
     "timestamp": 0.0,
     "disabled": False}
]
